### ISSUE TITLE
加载大pcap文件，程序卡死

### ISSUE THREAD

**Issue by muse117** [SurrealSky/PcapAnalyzer#1]
您好，我对您这个项目很感兴趣，于是运行测试了一下，发现加载了一个600多M的pcap文件，程序崩溃了

**Comment by SurrealSky** [comment]
> 
> 
> 您好，我对您这个项目很感兴趣，于是运行测试了一下，发现加载了一个600多M的pcap文件，程序崩溃了

性能问题吧，我测试一下。

**Comment by muse117** [comment]
> > 您好，我对您这个项目很感兴趣，于是运行测试了一下，发现加载了一个600多M的pcap文件，程序崩溃了
> 
> 性能问题吧，我测试一下。

应该是开辟一个缓存区，超出之后新的数据覆盖旧的数据就可以了，不用显示全部pcap文件内的数据，只做全文件的数据分析与统计。您用过科来的软件么？就是这样做的

**Comment by SurrealSky** [comment]
> 
> 
> > > 您好，我对您这个项目很感兴趣，于是运行测试了一下，发现加载了一个600多M的pcap文件，程序崩溃了
> > 
> > 
> > 性能问题吧，我测试一下。
> 
> 应该是开辟一个缓存区，超出之后新的数据覆盖旧的数据就可以了，不用显示全部pcap文件内的数据，只做全文件的数据分析与统计。您用过科来的软件么？就是这样做的

我这个自己研究写的，完全没考虑性能优化之类的，用的c++各种容器，性能很低，所以没有考虑一些使用场景。
